/**
 * @File Name          : ContentDocumentTriggerHandler.cls
 * @Description        : 
 * @Author             : abdool.miskin@sc-mauritius.com
 * @Group              : 
 * @Last Modified On   : 02-04-2021
 * @Modification Log   : 
 *===================================================================================
 * Ver         Date                           Author                  Modification
 *===================================================================================
 * 1.0    06/12/2019, 09:53:01     abdool.miskin@sc-mauritius.com    Initial Version
**/
public without sharing class helloworld {
    
    public static void helloworld(){
        System.debug('hello world');
        //trial 1 2 3 4 5
        fakeobject__c fk = new fakeObject__c();
        
    }
}