name: DELETE_SCRATCH_ORG
#Description:
#Build is donne manually on the branch created to develop the ticket to verify 
#if the build is done correctly before doing the merge with the original dev branch on github


#workflow_dispatch ==> allows for workflow to be launched manually
on:
  workflow_dispatch:
    inputs:
      Scratch_Org_Name:
        description: 'New ScratchOrg alias Name'
        required: true
        default: 'scrNew-org'
    

#Jobs start executing here
jobs:

#=======================================================================FIRST JOB=============================================================
  CREATE_AND_PUSH_TO_VERIFICATION_SCRATCHORG:
  
    #setup environment OS
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
 
      #Uses sfdx-actions as a library on github actions allowing us to use sfdx commands like in local
      #RUN this command to get sfdx-auth-url ==> sfdx force:org:display --targetusername <username>
      #sfdx-auth-url FORMAT ====> force://<refreshToken>@<instanceUrl> or force://<clientId>:<clientSecret>:<refreshToken>@<instanceUrl>
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          if: ${{github.event.inputs.Scratch_Org_Name == 'Gael-2021-02-09-Build-#7'}}
          sfdx-auth-url: force://${{secrets.CLIENTID_KOALA}}::${{secrets.REFRESH_TOKEN_KOALA}}@${{secrets.INSTANCE_URL_KOALA}}

      #========================= START SCRATCH ORG ====================================
              
      #STEP1.2: Delete scratch org
      - name: Delete scratch Org
        run: |
          sfdx force:org:display -u ${{ github.event.inputs.Scratch_Org_Name }} --verbose
          sfdx force:limits:api:display -u ${{secrets.USERNAME_KOALA}}          
          sfdx force:org:list --all
          sfdx force:org:delete -u ${{ github.event.inputs.Scratch_Org_Name }} --noprompt