name: Push changes to resilient Shark org
#Will start workflow when a new commit is pushed to online repo

on: [push]
#Jobs start executing here
jobs:
  Push_to_Resilient_Shark_Org:
    #setup environment
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      #Initializes destination org to push
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: force://${{secrets.CLIENTIDRESILIENTSHARK}}::${{secrets.REFRESHTOKENRESILIENTSHARK}}@${{secrets.INSTANCEURLRESILIENTSHARK}}
     
      # #========================= START SCRATCH ORG ====================================
      # #STEP1: Creates scratch org
      # - name: Create Verification Scratch Org before pushing
      #   run: |
      #     sfdx force:org:create -s -f config/project-scratch-def.json -a Verification-org
      #     sfdx force:org:open
      #     sfdx force:org:list --all
      # #STEP1.1: Usescratch org as verification org
      # - name: Push to Scratch Org and run all Tests
      #   run: |
      #     sfdx force:source:push
      #     sfdx force:apex:test:run -u Verification-org --resultformat human
      # #STEP1.2: Delete scratch org
      # - name: Delete scratch Org
      #   run: |
      #     sfdx force:org:delete -u Verification-org --noprompt

      # #=========================== STARTS BUILD TO DESTINATION ORG =====================  
      # - name: Push changes to resilient shark Org and re-run all tests
      #   run: |          
      #     sfdx force:org:list --all
      #     sfdx force:source:deploy -x manifest/package.xml -u gael.cangy@resilient-shark-47mjo0.com
      #     sfdx force:apex:test:run -u gael.cangy@resilient-shark-47mjo0.com --resultformat human
      #   #sfdx force:org:display --targetusername gael.cangy@resilient-shark-47mjo0.com

      - name: testing sfdx plugin
        run: |
          sfdx plugins:install sfdx-git-delta y
          echo "--- package.xml generated with added and modified metadata ---"
          cat package/package.xml
         