name: Push changes to resilient Shark org

on: [push]

jobs:
  Push_to_Resilient_Shark_Org:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master

      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: force://${{secrets.CLIENTIDRESILIENTSHARK}}::${{secrets.REFRESHTOKENRESILIENTSHARK}}@${{secrets.INSTANCEURLRESILIENTSHARK}}

      - name: Push changes to resilient shark Org
        run: |
          ls -a
          sfdx force:org:list --all
          sfdx force:source:deploy -x manifest/package.xml
          